on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Gofmt
      run: "if [[ $(gofmt -l ./{cmd,pkg}) ]] ; then exit 1 ; fi"

    - name: Staticcheck
      run: |
        wget -q https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_linux_amd64.tar.gz
        echo "93f7780f8710380037cecee8a49178de01c6153f19587c082abec4cc8637016c  staticcheck_linux_amd64.tar.gz" | sha256sum -c -
        tar zxf staticcheck_linux_amd64.tar.gz
        ./staticcheck/staticcheck ./{cmd,pkg}/...

    - name: Vet
      run: go vet ./{cmd,pkg}/...

    - name: Lint
      run: |
        # https://github.com/actions/setup-go/issues/14
        export PATH=${PATH}:`go env GOPATH`/bin
        go get -u golang.org/x/lint/golint
        golint ./{cmd,pkg}/...

    - name: Test
      run: go test -race ./{cmd,pkg}/...
